name: branch-protection-guard
on:
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/**"
      - ".github/branch-protection/**"
      - "scripts/admin/sync_branch_protection.ps1"
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/**"
      - ".github/branch-protection/**"

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compare required status checks with repo protection
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          pwsh -NoProfile -Command "Set-Location $PWD; ./scripts/admin/sync_branch_protection.ps1"