name: Notify on Gate24h failure
on:
  workflow_run:
    workflows: ["Gate 24h (paper supervised)"]
    types: [completed]
jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Telegram notify
        uses: appleboy/telegram-action@v0.1.4
        with:
          to:    ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
             Gate24h failed
            Repo: ${{ github.repository }}
            RunID: ${{ github.event.workflow_run.id }}
            Conclusion: ${{ github.event.workflow_run.conclusion }}
            URL: ${{ github.event.workflow_run.html_url }}
