name: Paper Pulse

on:
  workflow_dispatch:
    inputs:
      hours:
        description: 'Duration in hours (e.g., 4 or 24)'
        required: false
        default: '4'

jobs:
  pulse:
    runs-on: windows-latest
    timeout-minutes: 1440
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build $Env:GITHUB_WORKSPACE

      - name: Run paper pulse
        shell: pwsh
        run: |
          $hours = '${{ github.event.inputs.hours }}'
          if (-not $hours) { $hours = '4' }
          $art = Join-Path $env:RUNNER_TEMP 'botg_pulse_artifacts'
          New-Item -ItemType Directory -Path $art -Force | Out-Null
          & "${{ github.workspace }}\scripts\run_paper_pulse.ps1" -Hours ([int]$hours) -ArtifactPath $art -FillProb 0.9 -FeePerTrade 0.02 -GeneratePlots:$false 2>&1 | Tee-Object -FilePath (Join-Path $art 'pulse_stdout.log')

      - name: Upload pulse artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: paper-pulse-artifacts
          path: ${{ runner.temp }}\botg_pulse_artifacts

