name: smoke-selftest
on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'   # 08:00 ICT daily (adjust if needed)

jobs:
  selftest:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
        
      - name: Verify stdlib sqlite3
        shell: pwsh
        run: python -c "import sqlite3, sys; print('sqlite3 OK, version:', sqlite3.sqlite_version)"
        
      - name: PowerShell ops.ps1 self-test
        shell: pwsh
        working-directory: ${{ github.workspace }}
        env:
          CI_BLOCK_FAIL: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && '1' || '0' }}
        run: |
          Write-Host "=== Loading ops.ps1 ==="
          . .\scripts\ops.ps1
          
          Write-Host "=== Running self-test ==="
          .\scripts\ops_selftest.ps1
          
      - name: Upload self-test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selftest-results
          path: |
            scripts/ops_selftest.ps1
            .vscode/tasks.json
            docs/RUNBOOK_smoke60m.md
