name: smoke-fast
on:
  pull_request:
    branches:
      - dev
      - 'dev/**'
  workflow_dispatch:
jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build BotG.sln -c Release
      - name: Test
        run: dotnet test Tests/BotG.Tests.csproj -c Release --no-build --logger "trx;LogFileName=test_results.trx"
      - name: Quick smoke (1h->5min)
        shell: pwsh
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -File .\scripts\run_smoke.ps1 -Seconds 300 -ArtifactPath $env:RUNNER_TEMP\botg_artifact -FillProb 1.0 -DrainSeconds 30
      - name: Capture artifact path
        id: cap
        shell: pwsh
        run: |
          $run = Get-ChildItem -Path "$env:RUNNER_TEMP\botg_artifact" -Directory -Filter 'telemetry_run_*' -Recurse | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $run) { throw 'no telemetry_run found' }
          echo "run=$($run.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Sanity checks
        shell: pwsh
        run: |
          $run = '${{ steps.cap.outputs.run }}'
          if (-not (Test-Path -LiteralPath (Join-Path $run 'orders.csv'))) { throw 'orders.csv missing' }
          if (-not (Test-Path -LiteralPath (Join-Path $run 'reconcile_report.json'))) { throw 'reconcile_report.json missing' }
          $rr = Get-Content -LiteralPath (Join-Path $run 'reconcile_report.json') -Raw | ConvertFrom-Json
          if ([int]$rr.orphan_fills_count -gt 2) { throw "Too many orphan fills: $($rr.orphan_fills_count)" }
      - name: Upload smoke artifact
        uses: actions/upload-artifact@v4
        with:
          name: smoke-fast_artifact
          path: ${{ steps.cap.outputs.run }}