name: smoke-fast

on:
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --nologo
      - name: Tests
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
      - name: Run compressed smoke (5 min)
        id: run_smoke
        shell: pwsh
        run: |
          $out = Join-Path $env:TEMP ("botg_ci_smoke_" + (Get-Date -Format yyyyMMdd_HHmmss))
          New-Item -ItemType Directory -Path $out | Out-Null
          pwsh -NoProfile -ExecutionPolicy Bypass -File .\scripts\run_smoke.ps1 -SecondsPerHour 300 -Seconds 300 -DrainSeconds 30 -FillProbability 1.0 -UseSimulation -ArtifactPath $out
          $dir = Get-ChildItem -Path $out -Directory -Filter 'telemetry_run_*' | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $dir) { throw "No telemetry_run_* directory found in $out" }
          $rr = Join-Path $dir.FullName 'reconcile_report.json'
          if (-not (Test-Path -LiteralPath $rr)) { throw 'reconcile_report.json missing' }
          $json = Get-Content -LiteralPath $rr -Raw | ConvertFrom-Json
          if ([int]$json.orphan_fills_count -gt 0) { throw "Orphan fills detected: $($json.orphan_fills_count)" }
          "artifact_dir=$($dir.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-fast-telemetry
          path: ${{ steps.run_smoke.outputs.artifact_dir }}