name: smoke-selftest

concurrency:
  group: smoke-selftest-${{ github.ref }}
  cancel-in-progress: true

on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'   # 08:00 ICT daily (adjust if needed)

jobs:
  selftest:
    runs-on: windows-latest
    timeout-minutes: 12
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
        
      - name: Verify stdlib sqlite3
        shell: pwsh
        run: python -c "import sqlite3, sys; print('sqlite3 OK, version:', sqlite3.sqlite_version)"
        
      - name: PowerShell ops.ps1 self-test
        shell: pwsh
        working-directory: ${{ github.workspace }}
        env:
          CI_BLOCK_FAIL: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && '1' || '0' }}
        run: |
          Write-Host "=== Loading ops.ps1 ==="
          . .\scripts\ops.ps1
          
          Write-Host "=== Running self-test ==="
          .\scripts\ops_selftest.ps1
          
      - name: Summarize health-check
        id: sum
        if: always()
        shell: pwsh
        run: |
          $folder = Join-Path $PWD 'artifacts_ascii'
          $latest = Get-ChildItem $folder -Filter 'health_check_*.json' -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $latest) {
            "### Smoke selftest summary`n_No health JSON found_" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
            "status=UNKNOWN" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
            "issues_count=0" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
            exit 0
          }
          $j = Get-Content $latest.FullName -Raw | ConvertFrom-Json
          $issues = @($j.issues) | Where-Object { $_ } 
          $issuesMd = if ($issues.Count -gt 0) { ($issues | ForEach-Object { "- $_" }) -join "`n" } else { "_None_" }
          @"
        ### Smoke selftest summary
        - **STATUS**: $($j.STATUS)
        - **Can continue**: $($j.can_continue_running)
        - **Reconstruct tool**: $($j.reconstruct_tool.present) ($($j.reconstruct_tool.path))
        - **Issues**:
        $issuesMd
        "@ | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
          "status=$($j.STATUS)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          "issues_count=$($issues.Count)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Comment summary on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = [
              '### Smoke selftest (auto-summary)',
              `**STATUS**: ${{ steps.sum.outputs.status }}`,
              `**Issues**: ${{ steps.sum.outputs.issues_count }}`,
              '',
              '> Full details are in the job summary and artifacts.'
            ].join('\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });

      - name: Upload self-test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selftest-results
          retention-days: 7
          path: |
            scripts/ops_selftest.ps1
            .vscode/tasks.json
            docs/RUNBOOK_smoke60m.md
