-n-a-m-e-:- -s-m-o-k-e---f-a-s-t--
--
-o-n-:--
- - -p-u-l-l-_-r-e-q-u-e-s-t-:--
- - - - -b-r-a-n-c-h-e-s-:- -[- -m-a-i-n-,- -d-e-v- -]--
- - - - -t-y-p-e-s-:- -[- -o-p-e-n-e-d-,- -s-y-n-c-h-r-o-n-i-z-e-,- -r-e-o-p-e-n-e-d- -]--
- - -w-o-r-k-f-l-o-w-_-d-i-s-p-a-t-c-h-:--
--
-j-o-b-s-:--
- - -s-m-o-k-e-:--
- - - - -r-u-n-s---o-n-:- -w-i-n-d-o-w-s---l-a-t-e-s-t--
- - - - -s-t-e-p-s-:--
- - - - - - --- -n-a-m-e-:- -C-h-e-c-k-o-u-t--
- - - - - - - - -u-s-e-s-:- -a-c-t-i-o-n-s-/-c-h-e-c-k-o-u-t-@-v-4--
- - - - - - --- -n-a-m-e-:- -S-e-t-u-p- -.-N-E-T--
- - - - - - - - -u-s-e-s-:- -a-c-t-i-o-n-s-/-s-e-t-u-p---d-o-t-n-e-t-@-v-4--
- - - - - - - - -w-i-t-h-:--
- - - - - - - - - - -d-o-t-n-e-t---v-e-r-s-i-o-n-:- -'-6-.-0-.-x-'--
- - - - - - --- -n-a-m-e-:- -R-e-s-t-o-r-e--
- - - - - - - - -r-u-n-:- -d-o-t-n-e-t- -r-e-s-t-o-r-e--
- - - - - - --- -n-a-m-e-:- -B-u-i-l-d--
- - - - - - - - -r-u-n-:- -d-o-t-n-e-t- -b-u-i-l-d- -----c-o-n-f-i-g-u-r-a-t-i-o-n- -R-e-l-e-a-s-e- -----n-o-l-o-g-o--
- - - - - - --- -n-a-m-e-:- -T-e-s-t-s--
- - - - - - - - -r-u-n-:- -d-o-t-n-e-t- -t-e-s-t- -----c-o-n-f-i-g-u-r-a-t-i-o-n- -R-e-l-e-a-s-e- -----n-o---b-u-i-l-d- -----l-o-g-g-e-r- -"-t-r-x-;-L-o-g-F-i-l-e-N-a-m-e-=-t-e-s-t-_-r-e-s-u-l-t-s-.-t-r-x-"--
- - - - - - --- -n-a-m-e-:- -R-u-n- -c-o-m-p-r-e-s-s-e-d- -s-m-o-k-e- -(-5- -m-i-n-)--
- - - - - - - - -i-d-:- -r-u-n-_-s-m-o-k-e--
- - - - - - - - -s-h-e-l-l-:- -p-w-s-h--
- - - - - - - - -r-u-n-:- -|--
- - - - - - - - - - -$-o-u-t- -=- -J-o-i-n---P-a-t-h- -$-e-n-v-:-T-E-M-P- -(-"-b-o-t-g-_-c-i-_-s-m-o-k-e-_-"- -+- -(-G-e-t---D-a-t-e- ---F-o-r-m-a-t- -y-y-y-y-M-M-d-d-_-H-H-m-m-s-s-)-)--
- - - - - - - - - - -N-e-w---I-t-e-m- ---I-t-e-m-T-y-p-e- -D-i-r-e-c-t-o-r-y- ---P-a-t-h- -$-o-u-t- -|- -O-u-t---N-u-l-l--
- - - - - - - - - - -&- -"-$-{-{- -g-i-t-h-u-b-.-w-o-r-k-s-p-a-c-e- -}-}-\-s-c-r-i-p-t-s-\-r-u-n-_-s-m-o-k-e-.-p-s-1-"- ---S-e-c-o-n-d-s-P-e-r-H-o-u-r- -3-0-0- ---S-e-c-o-n-d-s- -3-0-0- ---D-r-a-i-n-S-e-c-o-n-d-s- -3-0- ---F-i-l-l-P-r-o-b-a-b-i-l-i-t-y- -1-.-0- ---U-s-e-S-i-m-u-l-a-t-i-o-n- ---A-r-t-i-f-a-c-t-P-a-t-h- -$-o-u-t--
- - - - - - - - - - -$-d-i-r- -=- -G-e-t---C-h-i-l-d-I-t-e-m- ---P-a-t-h- -$-o-u-t- ---D-i-r-e-c-t-o-r-y- ---F-i-l-t-e-r- -'-t-e-l-e-m-e-t-r-y-_-r-u-n-_-*-'- -|- -S-o-r-t---O-b-j-e-c-t- -L-a-s-t-W-r-i-t-e-T-i-m-e- ---D-e-s-c-e-n-d-i-n-g- -|- -S-e-l-e-c-t---O-b-j-e-c-t- ---F-i-r-s-t- -1--
- - - - - - - - - - -i-f- -(---n-o-t- -$-d-i-r-)- -{- -t-h-r-o-w- -"-N-o- -t-e-l-e-m-e-t-r-y-_-r-u-n-_-*- -d-i-r-e-c-t-o-r-y- -f-o-u-n-d- -i-n- -$-o-u-t-"- -}--
- - - - - - - - - - -$-r-r- -=- -J-o-i-n---P-a-t-h- -$-d-i-r-.-F-u-l-l-N-a-m-e- -'-r-e-c-o-n-c-i-l-e-_-r-e-p-o-r-t-.-j-s-o-n-'--
- - - - - - - - - - -i-f- -(---n-o-t- -(-T-e-s-t---P-a-t-h- ---L-i-t-e-r-a-l-P-a-t-h- -$-r-r-)-)- -{- -t-h-r-o-w- -'-r-e-c-o-n-c-i-l-e-_-r-e-p-o-r-t-.-j-s-o-n- -m-i-s-s-i-n-g-'- -}--
- - - - - - - - - - -$-j-s-o-n- -=- -G-e-t---C-o-n-t-e-n-t- ---L-i-t-e-r-a-l-P-a-t-h- -$-r-r- ---R-a-w- -|- -C-o-n-v-e-r-t-F-r-o-m---J-s-o-n--
- - - - - - - - - - -i-f- -(-[-i-n-t-]-$-j-s-o-n-.-o-r-p-h-a-n-_-f-i-l-l-s-_-c-o-u-n-t- ---g-t- -0-)- -{- -t-h-r-o-w- -"-O-r-p-h-a-n- -f-i-l-l-s- -d-e-t-e-c-t-e-d-:- -$-(-$-j-s-o-n-.-o-r-p-h-a-n-_-f-i-l-l-s-_-c-o-u-n-t-)-"- -}--
- - - - - - - - - - -$-r-e-c-o-n- -=- -J-o-i-n---P-a-t-h- -$-d-i-r-.-F-u-l-l-N-a-m-e- -'-r-e-c-o-n-s-t-r-u-c-t-_-r-e-p-o-r-t-.-j-s-o-n-'--
- - - - - - - - - - -i-f- -(---n-o-t- -(-T-e-s-t---P-a-t-h- ---L-i-t-e-r-a-l-P-a-t-h- -$-r-e-c-o-n-)-)- -{- -t-h-r-o-w- -'-r-e-c-o-n-s-t-r-u-c-t-_-r-e-p-o-r-t-.-j-s-o-n- -m-i-s-s-i-n-g-'- -}--
- - - - - - - - - - -$-r-j-s-o-n- -=- -G-e-t---C-o-n-t-e-n-t- ---L-i-t-e-r-a-l-P-a-t-h- -$-r-e-c-o-n- ---R-a-w- -|- -C-o-n-v-e-r-t-F-r-o-m---J-s-o-n--
- - - - - - - - - - -i-f- -(-[-i-n-t-]-$-r-j-s-o-n-.-o-r-p-h-a-n-_-a-f-t-e-r- ---g-t- -0-)- -{- -t-h-r-o-w- -"-R-e-c-o-n-s-t-r-u-c-t- -o-r-p-h-a-n-_-a-f-t-e-r- ->- -0-:- -$-(-$-r-j-s-o-n-.-o-r-p-h-a-n-_-a-f-t-e-r-)-"- -}--
- - - - - - - - - - -"-a-r-t-i-f-a-c-t-_-d-i-r-=-$-(-$-d-i-r-.-F-u-l-l-N-a-m-e-)-"- -|- -O-u-t---F-i-l-e- ---F-i-l-e-P-a-t-h- -$-e-n-v-:-G-I-T-H-U-B-_-O-U-T-P-U-T- ---A-p-p-e-n-d--
- - - - - - --- -n-a-m-e-:- -U-p-l-o-a-d- -a-r-t-i-f-a-c-t-s--
- - - - - - - - -i-f-:- -a-l-w-a-y-s-(-)--
- - - - - - - - -u-s-e-s-:- -a-c-t-i-o-n-s-/-u-p-l-o-a-d---a-r-t-i-f-a-c-t-@-v-4--
- - - - - - - - -w-i-t-h-:--
- - - - - - - - - - -n-a-m-e-:- -s-m-o-k-e---f-a-s-t---t-e-l-e-m-e-t-r-y--
- - - - - - - - - - -p-a-t-h-:- -$-{-{- -s-t-e-p-s-.-r-u-n-_-s-m-o-k-e-.-o-u-t-p-u-t-s-.-a-r-t-i-f-a-c-t-_-d-i-r- -}-}--
-