name: Gate24h watchdog (10min)
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest Gate24h status
        id: s
        uses: actions/github-script@v7
        with:
          script: |
            const wf = "gate24h_main.yml";
            const r = (await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner, repo: context.repo.repo, workflow_id: wf, per_page: 1
            })).data.workflow_runs[0];
            const q = (Date.now()-new Date(r.created_at))/60000;
            core.setOutput('status', r.status||'');
            core.setOutput('conclusion', r.conclusion||'');
            core.setOutput('id', r.id); core.setOutput('url', r.html_url);
            core.setOutput('queued', q.toFixed(0));
      - name: Telegram alert on failure/long-queue
        if: steps.s.outputs.conclusion != 'success' || (steps.s.outputs.status == 'queued' && fromJSON(steps.s.outputs.queued) > 10)
        uses: appleboy/telegram-action@v0.1.4
        with:
          to:    ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
             Gate24h watchdog
            Status: ${{ steps.s.outputs.status }}
            Conclusion: ${{ steps.s.outputs.conclusion }}
            Queued(min): ${{ steps.s.outputs.queued }}
            RunID: ${{ steps.s.outputs.id }}
            URL: ${{ steps.s.outputs.url }}
